"""Added invitation table.

Revision ID: 4f5ec3f0ac37
Revises:
Create Date: 2022-03-18 11:33:37.013026
"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4f5ec3f0ac37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'invitation',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('invitation_code', sa.String(), nullable=True),
        sa.Column('expiry_timestamp', sa.DateTime(), nullable=True),
        sa.Column('create_timestamp', sa.DateTime(), nullable=True),
        sa.Column('invited_by', sa.String(), nullable=True),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('platform_role', sa.String(), nullable=True),
        sa.Column('project_role', sa.String(), nullable=True),
        sa.Column('project_id', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
        schema='pilot_invitation',
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invitation', schema='pilot_invitation')
    # ### end Alembic commands ###
