"""Adding event table

Revision ID: c50577f5d93e
Revises: e86797550c26
Create Date: 2022-04-06 09:41:48.967807

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c50577f5d93e'
down_revision = 'e86797550c26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_event',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('target_user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('target_user', sa.String(), nullable=True),
    sa.Column('operator_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('operator', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    schema='pilot_event'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_event', schema='pilot_event')
    # ### end Alembic commands ###
