name: Build and Publish

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    env:
      commit_SHA: ${GITHUB_SHA:7}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: indoc-devops
          password: ${{ secrets.GHCR_PAT }}
      - name: show the commit sha for the image tag
        run: echo ${GITHUB_SHA:7}
      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: .
          # Note: tags has to be all lower-case
          tags: |
            ghcr.io/pilotdataplatform/auth:$commit_SHA
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/develop' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
