name: Trigger Jenkins

on:
  workflow_run:
    workflows: ["Build and Publish"]
    types:
      - completed

jobs:
  Trigger:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Trigger jenkins job
    runs-on: ubuntu-latest
    steps:
      - name: echo commit sha
        run:  full_commit_SHA="${{ github.event.workflow_run.head_sha }}" && short_commit_SHA=$(echo "${full_commit_SHA:0:7}") && echo $short_commit_SHA
      - name: trigger the jenkins pipeline with curl
        run: location=$(curl -i -X POST -m 60 -L --user jenkins:${{ secrets.JENKINS_API_TOKEN }} https://ci.dev.pilot.indocresearch.org/job/Infra/job/UpdateAppVersion/buildWithParameters --data TF_TARGET_ENV=dev --data TARGET_RELEASE=auth --data NEW_APP_VERSION="$short_commit_SHA" | grep location | cut -d " " -f2) && echo $location
